### ISSUE TITLE
Can node-nmea be used in react native ?

### ISSUE THREAD

**Issue by esutton** [jamesp/node-nmea#18]
I am new to Node.js and react native.  

I ran  https://github.com/jamesp/node-nmea/blob/master/test.js on Android device and all tests returned valid: false.  Is false expected for this test.js?

This online decoder did not seem to complain ( but did not recognize all messages ).
    http://freenmea.net/decoder

```
ReactNativeJS: { raw: '$GPGSA,A,1,,,,,,,,,,,,,,,*1E', valid: false }
ReactNativeJS: { raw: '$GPGSV,3,1,12,29,75,266,39,05,48,047,,26,43,108,,15,35,157,*78',
ReactNativeJS:   valid: false }
ReactNativeJS: { raw: '$GPGSV,3,2,12,21,30,292,,18,21,234,,02,18,093,,25,13,215,*7F',
ReactNativeJS:   valid: false }
ReactNativeJS: { raw: '$GPGSV,3,3,12,30,11,308,,16,,333,,12,,191,,07,-4,033,*62',
ReactNativeJS:   valid: false }
ReactNativeJS: { raw: '$GPRMC,085542.023,V,,,,,,,041211,,,N*45', valid: false }
08-16 10:38:04.824 20231 20902 D BluetoothIOModule: BluetoothDevice: TK_0003, 00:07:80:46:87:CD
ReactNativeJS: { raw: '$GPGGA,085543.023,,,,,0,00,,,M,0.0,M,,0000*58',
ReactNativeJS:   valid: false }
ReactNativeJS: { raw: '$IIBWC,160947,6008.160,N,02454.290,E,162.4,T,154.3,M,001.050,N,DEST*1C',
ReactNativeJS:   valid: false }
ReactNativeJS: { raw: '$IIAPB,A,A,0.001,L,N,V,V,154.3,M,DEST,154.3,M,154.2,M*19',
ReactNativeJS:   valid: false }
ReactNativeJS: { raw: '$IIHDM,201.5,M*24', valid: false }
```

```

{
  "name": "BluetoothIOExample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "base-64": "^0.1.0",
    "buffer": "^4.7.1",
    "node-nmea": "^1.0.2",
    "react": "15.2.1",
    "react-native": "^0.31.0",
    "react-native-bluetooth-io": "file:../",
    "react-native-vector-icons": "^2.0.3",
    "utf8": "^2.1.1"
  }
}

```

Thank you for sharing your work!

I like the way you organized the codec modules.

**Comment by esutton** [comment]
Never mind. All is good.

When I tried the following, I downloade some other npm published project:
`npm install node-nmea --save`

I changed to:

```
{
  "name": "BluetoothIOExample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "base-64": "^0.1.0",
    "buffer": "^4.7.1",
    "node-nmea": "git+https://github.com/jamesp/node-nmea",
    "react": "15.2.1",
    "react-native": "^0.31.0",
    "react-native-bluetooth-io": "file:../",
    "react-native-vector-icons": "^2.0.3",
    "utf8": "^2.1.1"
  }
}

```

**Comment by tkurki** [comment]
Just on the off change you might be interested: are you aware of http://signalk.org/ and for example https://github.com/SignalK/instrumentpanel ?

The reason I am asking is that I would love to have (react-)native Signal K apps!

**Comment by esutton** [comment]
Thank you for the links. Nice looking widgets. 

The demos are beautiful.
- http://signalk.org/demo.html

I wish I understood how to make Node.js components compatible with react-native using D3 or whatever they are using to draw instrument panels.

Very impressive!

**Comment by tkurki** [comment]
The gauges are mostly hand crafted svg, not (much) D3 magic involved. https://www.npmjs.com/package/react-native-svg looks interesting.

Sorry, this is getting awfully off topic here...

**Comment by esutton** [comment]
I agree https://www.npmjs.com/package/react-native-svg is a good approach.

In case you might even need D3 charting in React or RN:

This project is looking good:
- https://formidable.com/open-source/victory/
