### ISSUE TITLE
Error when parsing data

### ISSUE THREAD

**Issue by jeebee2013** [jamesp/node-nmea#19]
Hello 
i've got this error when trying the code

{ sentence: 'GSV',
  type: 'satellite-list-partial',
  numMsgs: 3,
  msgNum: 1,
  satsInView: 12,
  satellites: 
   [ { id: '08', elevationDeg: 85, azimuthTrue: 237, SNRdB: 19 },
     { id: '11', elevationDeg: 51, azimuthTrue: 294, SNRdB: 34 },
     { id: '27', elevationDeg: 49, azimuthTrue: 136, SNRdB: 18 },
     { id: '01', elevationDeg: 39, azimuthTrue: 280, SNRdB: 33 } ],
  talker_id: 'GP' }
/home/julien/node_modules/nmea/nmea.js:81
    throw Error("Invalid line:" + line);
    ^

Error: Invalid line:$GPGSV,3,2,12,10,37,050,19,22,31,215,15,16,06,181,08,28,15,3

no error when i don't parse the data 
console.log(line)
so error shoud come from parsing...
i'm using a GlobalSat GPS under a ubuntu 16.X

any idea.

thanks

**Comment by ricardoboss** [comment]
Did you remove the checksum? Every NMEA sentence should end with `*xx<CR><LF>` whereas `xx` are two hexadecimal digits.
